In [ ]:
for i in range (0,10):

  print('i=',i)

i= 0
i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9


In [ ]:
x=10
y=5
c=x+y
print('c=',c)

c= 15


In [ ]:
for j in range (3,10,1):
  print('j=',j,',',end='')
print('')
for k in range(0,10,2):
  print('k=',k,end='')



j= 3 ,j= 4 ,j= 5 ,j= 6 ,j= 7 ,j= 8 ,j= 9 ,
k= 0k= 2k= 4k= 6k= 8

In [ ]:
x=0
while x<5:
  x+=1
  print('x=',x)
print('End of the loop')

x= 1
x= 2
x= 3
x= 4
x= 5
End of the loop


In [ ]:
x=41
y=59
z=100
c=x+y

if c==z:
  print('c=z')
elif c<z:
  print('c<z')
else :
  print('c>z')



c=z


In [ ]:
A=[1,2,3]
for i in range (4,11):
  A.append(i)
  print('A=',A)

A= [1, 2, 3, 4]
A= [1, 2, 3, 4, 5]
A= [1, 2, 3, 4, 5, 6]
A= [1, 2, 3, 4, 5, 6, 7]
A= [1, 2, 3, 4, 5, 6, 7, 8]
A= [1, 2, 3, 4, 5, 6, 7, 8, 9]
A= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
A=[1,2,3]
B=A
print('A=',A)
print('B=',B)
B=A[:]
A[0]=100
print('A=',A)
print('B=',B)

A= [1, 2, 3]
B= [1, 2, 3]
A= [100, 2, 3]
B= [1, 2, 3]


In [ ]:
import numpy as np
A=[[1,2,3],[4,5,6],[7,8,9]]
print('A=',A)
B=[[2,0,0],[0,2,0],[0,0,2]]
C=np.matmul(A,B)
print('C=',C)
D=np.dot(A,B)
print('D=',D)

x=[1,7,3]
V=np.dot(A,x)
print('A*x^T=',V)



A= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
C= [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
D= [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
A*x^T= [24 57 90]


In [ ]:
import numpy as np
Anp=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('column:',Anp[:,2],A[:][2])

column: [3 6 9] [7, 8, 9]


In [ ]:
x=0.1
y=0.2
z=0.3

a=x+y
if z==a:
  print('z is equal to a')
else:
  print('z is not equal to a')


z is not equal to a


In [ ]:
x=(0.8+0.1)+0.3
y=0.8+(0.1+0.3)
c=10**16
z=(1-x/y)*c
print('z=',z)

z= 2.220446049250313


In [ ]:
e=1021
x=2.**e
for i in range (0,3):
 e+=1
 x=2.**e
 y=1/x
 z=x/x

print('e=',e,'x=',x,'y=',y,'z=',z)

OverflowError: (34, 'Numerical result out of range')