In [ ]:
A=[1,2,3]

for i in range(4,11,1):
  A.append(i)
  print('A=',A)



A= [1, 2, 3, 4]
A= [1, 2, 3, 4, 5]
A= [1, 2, 3, 4, 5, 6]
A= [1, 2, 3, 4, 5, 6, 7]
A= [1, 2, 3, 4, 5, 6, 7, 8]
A= [1, 2, 3, 4, 5, 6, 7, 8, 9]
A= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
A=[1,2,3]

B=A
print('B=',B)
print('A=',A)

A[0]=100
print('A=',A)
print('B=',B)




B= [1, 2, 3]
A= [1, 2, 3]
A= [100, 2, 3]
B= [100, 2, 3]


In [ ]:
A=[1,2,3]

B=A
print('B=',B)
print('A=',A)
B=A[:]
A[0]=100
print('A=',A)
print('B=',B)

B= [1, 2, 3]
A= [1, 2, 3]
A= [100, 2, 3]
B= [1, 2, 3]


In [ ]:
import numpy as np
A=[[1,2,3],[4,5,6],[7,8,9]]
B=[[0,0,1],[8,9,7],[6,4,2]]

C=np.matmul(A,B)
print('C=',C)
D=np.dot(A,B)
print('')
print('D=',D)
x=[1,7,8]
E=np.dot(A,x)
print('A*x^T=',x)
R=A[1][:]
print('Row 2 =',R)

C= [[ 34  30  21]
 [ 76  69  51]
 [118 108  81]]

D= [[ 34  30  21]
 [ 76  69  51]
 [118 108  81]]
A*x^T= [1, 7, 8]
Row 2 = [4, 5, 6]


In [ ]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('column 1=',A[:,0])



column 1= [1 4 7]


In [ ]:
x=(0.9+0.25)+0.6
y=0.9+(0.25+0.6)
z=10**16
o=(1-x/y)*z
print('output=',o)

output= 0.0


In [ ]:
e=1021
c=2**e
for i in range (0,3):
  e+=1
  a=x/x
  b=1/c
  print('a=',a,'','b=',b)

a= 1.0  b= 2.2250738585072014e-308
a= 1.0  b= 2.2250738585072014e-308
a= 1.0  b= 2.2250738585072014e-308


In [12]:
A=[[2,1,-1],[4,0,-1],[-8,2,2]]
b=[6,6,-8]

m=[[0]*3 for i in range(3)]
m[0][0]=1
m[1][1]=1
m[2][2]=1


indicator=1
if A[0][0]!=0:

  m[1][0]=A[1][0]/A[0][0]
  m[2][0]=A[2][0]/A[0][0]

  A1=[[0]*3 for i in range(3)]
  b1=[0,0,0]
  A1[0][0]=A[0][0]
  A1[0][1]=A[0][1]
  A1[0][2]=A[0][2]
  b[0]=b1[0]

  A1[1][1]=A[1][1]-m[1][0]*A[0][1]
  A1[1][2]=A[1][2]-m[1][0]*A[0][2]
  A1[2][1]=A[2][1]-m[2][0]*A[0][1]
  A1[2][2]=A[2][2]-m[2][0]*A[0][2]
  b1[1]=b[1]-m[1][0]*b[0]
  b1[2]=b[2]-m[2][0]*b[0]

else:
  indicator=0
  print('method fails')

def backsubstitution(U,b):
  x=[0,0,0]
  x[2]=b[2]/U[2][2]
  x[1]=(b[1]-U[1][2]*x[2])/U[1][1]
  x[0]=(b[0]-U[0][2]*x[2]-U[0][1]*x[1])/U[0][0]

  return x






if indicator:
  A2=[[0]*3 for i in range(3)]
  b2=[0,0,0]
  A2[0][0]=A1[0][0]
  A2[0][1]=A1[0][1]
  A2[0][2]=A1[0][2]
  A2[1][0]=A1[1][0]
  A2[1][1]=A1[1][1]
  A2[1][2]=A1[1][2]
  b2[0]=b1[0]
  b2[1]=b1[1]

  if A1[1][1]!=0:
    m[2][1]=A1[2][1]/A1[1][1]
    A2[2][2]=A1[2][2]-m[2][1]*A1[1][2]
    b2[2]=b1[2]-m[2][1]*b1[1]

    if A[2][2]!=0:
      x=backsubstitution(A2,b2)
      print('The solution of given system is',x)


    else:
      print('oops method still failed.')





















The solution of given system is [4.0, 2.0, 10.0]
